export const COLORS=['#e1ae57','#6ba7df','#d884a0','#a59ae0'];
export const LEVELS=['Bo‘sh yer','Choyxona','Kafe','Restoran','To‘yxona'];
export const GROUPS=['Bozorlar','Savdo markazlari','Tarixiy shaharlar','Supermarketlar','Sanoat','Avtomobilsozlik','Shahar maskanlari','Premium hududlar'];
export const GROUP_COLORS=['#956849','#71bddd','#d182ab','#e89b52','#d97068','#d7bd50','#64a486','#708cd1'];
export type Tile={id:number;name:string;short:string;kind:'property'|'transport'|'utility'|'card'|'tax'|'start'|'jail'|'rest'|'gojail';group?:number;price:number;build:number;rent:number[];icon:string};
const raw:[string,string,Tile['kind'],number,string][]=[
['Start — Baraka boshlanishi','START','start',-1,'flag'],['Chorsu bozori','Chorsu','property',0,'shop'],['Taqdir','Taqdir','card',-1,'card'],['O‘rikzor bozori','O‘rikzor','property',0,'shop'],['Soliq inspeksiyasi','Soliq','tax',-1,'tax'],['Toshkent Metropoliteni','Metro','transport',-1,'train'],['Qo‘yliq bozori','Qo‘yliq','property',1,'shop'],['Imkoniyat','Imkoniyat','card',-1,'spark'],['Abu Sahiy','Abu Sahiy','property',1,'shop'],['HETK — Elektr','Elektr','utility',-1,'bolt'],['Qamoq / Mehmon','Qamoq','jail',-1,'lock'],['Xorazm — Ichan Qal’a','Xorazm','property',2,'landmark'],['Hududgazta’minot','Gaz','utility',-1,'flame'],['Buxoro — Minorai Kalon','Buxoro','property',2,'landmark'],['Samarqand — Registon','Samarqand','property',2,'landmark'],['Afrosiyob poyezdi','Afrosiyob','transport',-1,'train'],['Korzinka','Korzinka','property',3,'cart'],['Taqdir','Taqdir','card',-1,'card'],['Makro','Makro','property',3,'cart'],['Havas','Havas','property',3,'cart'],['Choy ustida dam olish','Dam olish','rest',-1,'coffee'],['Artel','Artel','property',4,'factory'],['Imkoniyat','Imkoniyat','card',-1,'spark'],['Akfa','Akfa','property',4,'factory'],['Imzo','Imzo','property',4,'factory'],['Uzbekistan Airways','Airways','transport',-1,'plane'],['UzAuto Motors','UzAuto','property',5,'car'],['SamAvto','SamAvto','property',5,'car'],['Toshkent Shahar Suv Ta’minoti','Suv','utility',-1,'water'],['BYD Uzbekistan','BYD','property',5,'car'],['Qamoqqa boring','Qamoqqa!','gojail',-1,'shield'],['Amir Temur xiyoboni','Amir Temur','property',6,'tree'],['Tashkent City','Tashkent City','property',6,'building'],['Taqdir','Taqdir','card',-1,'card'],['Magic City','Magic City','property',6,'spark'],['Yandex Go','Yandex Go','transport',-1,'car'],['Imkoniyat','Imkoniyat','card',-1,'spark'],['IT Park Uzbekistan','IT Park','property',7,'building'],['Mulk solig‘i','Mulk solig‘i','tax',-1,'tax'],['Humo Arena','Humo Arena','property',7,'trophy']];
const prices=[600000,1000000,1400000,2000000,2400000,2800000,3200000,3800000];
export const BOARD:Tile[]=raw.map(([name,short,kind,group,icon],id)=>{const offset=raw.slice(0,id).filter(x=>x[3]===group&&group>=0).length;const price=kind==='property'?prices[group]+offset*200000:kind==='transport'?2000000:kind==='utility'?1500000:0;const base=kind==='property'?Math.round(price*(group===0?.035:group===7?.12:.075)/10000)*10000:0;return {id,name,short,kind,group:group<0?undefined:group,price,build:group<0?0:500000+Math.floor(group/2)*500000,rent:[base,base*5,base*14,base*28,base*40],icon}});
export type Player={id:string;name:string;bot:boolean;token?:number;cash:number;pos:number;laps:number;jailed:boolean;jailAttempts:number;bankrupt:boolean;passes:number};
export type Asset={owner:string|null;level:number;mortgaged:boolean};
export type Card={title:string;text:string;amount?:number;usd?:number;effect?:'jail'|'pass'|'start'};
export const CARDS:Card[]=[
{title:'Davlat granti',text:'Biznes loyihangiz davlat grantini yutdi!',amount:2000000},
{title:'Bojxonada ushlanib qoldi',text:'Tovaringiz bojxonada qolib ketdi. 125 dollar miqdorida to‘lov.',usd:-125},
{title:'Gentra muborak!',text:'Qarzga mashina oldingiz. Bankka bir martalik to‘lov.',amount:-3000000},
{title:'Qovun pishig‘i',text:'Dehqonchilikdan barakali foyda oldingiz.',amount:1000000},
{title:'Radarga tushdingiz',text:'Yo‘l qoidalariga amal qiling. Jarima to‘laysiz.',amount:-300000},
{title:'Jiyaningizning to‘yi',text:'To‘yga to‘yona va sovg‘alar xarajati.',amount:-1200000},
{title:'Qalin puli',text:'Oilaviy marosim uchun xarajat qilasiz.',amount:-2000000},
{title:'Tanish-bilish',text:'Ushbu kartani saqlang. Bitta soliq to‘lovidan ozod qiladi.',effect:'pass'},
{title:'Tekshiruv boshlandi',text:'Qamoqqa boring. Start bonusi berilmaydi.',effect:'jail'},
{title:'Baraka sari',text:'Startga boring va 2 000 000 so‘m oling.',effect:'start'},
{title:'Eksport shartnomasi',text:'Yangi mijoz bilan muvaffaqiyatli shartnoma!',amount:1500000},
{title:'Mahalla hashari',text:'Mahallani obodonlashtirishga hissa qo‘shdingiz.',amount:-500000},
{title:'Navro‘z savdosi',text:'Bayram savdosidan qo‘shimcha daromad.',amount:800000},
{title:'Tom ta’miri',text:'Do‘kon tomini ta’mirlash kerak.',amount:-700000},
{title:'Soliq maslahatchisi',text:'Tanish-bilish kartasi: bitta soliqdan ozod bo‘ling.',effect:'pass'},
{title:'Omadli investitsiya',text:'Sarmoyangiz foyda keltirdi.',amount:1200000}];
export type Phase='roll'|'purchase'|'card'|'tax'|'debt'|'end'|'auction'|'won';
export type Action={type:'roll'|'buy'|'skip'|'ack'|'payTax'|'usePass'|'payJail'|'end'|'build'|'sell'|'mortgage'|'redeem'|'bankrupt'|'bid'|'pass';tile?:number};
export type LogEvent={key:string;[key:string]:string|number};
export type State={v:1;revision:number;players:Player[];turn:number;phase:Phase;assets:Record<number,Asset>;dice:[number,number];doubles:number;extra:boolean;inflation:number;turnNo:number;log:{id:number;text:string;kind:string;event?:LogEvent}[];seq:number;card:number|null;decks:number[][];tax:number;debt:null|{amount:number;creditor:string|null;resume:'end'|'roll'|'move';steps:number};auction:null|{tile:number;current:string;bid:number;highest:string|null;passed:string[]};lastMove:null|{id:number;player:string;from:number;to:number;steps:number};rollId:number;winner:string|null};
export const money=(v:number)=>new Intl.NumberFormat('uz-UZ').format(v)+' so‘m';
export const compact=(v:number)=>v>=1000000?(v/1000000).toLocaleString('uz-UZ',{maximumFractionDigits:2})+' mln':(v/1000).toLocaleString('uz-UZ',{maximumFractionDigits:0})+' ming';
const shuffle=(a:number[],rng:()=>number)=>{for(let i=a.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
export function newGame(input:{name:string;bot:boolean;id?:string;token?:number}[],rng:()=>number=Math.random):State{if(input.length<2||input.length>4)throw Error('2–4 o‘yinchi kerak');return {v:1,revision:0,players:input.map((p,i)=>({id:p.id??'p'+i,name:p.name.trim().slice(0,24)||'O‘yinchi '+(i+1),bot:p.bot,token:p.token??i,cash:15000000,pos:0,laps:0,jailed:false,jailAttempts:0,bankrupt:false,passes:0})),turn:0,phase:'roll',assets:Object.fromEntries(BOARD.filter(t=>t.price).map(t=>[t.id,{owner:null,level:0,mortgaged:false}])),dice:[1,1],doubles:0,extra:false,inflation:0,turnNo:1,log:[{id:0,text:'Davra boshlandi. Har bir o‘yinchiga 15 mln so‘m. Omad!',kind:'start',event:{key:'start'}}],seq:0,card:null,decks:[shuffle([0,2,4,5,6,8,11,13],rng),shuffle([1,3,7,9,10,12,14,15],rng)],tax:0,debt:null,auction:null,lastMove:null,rollId:0,winner:null}}
export function current(s:State){return s.players[s.turn]}
export function actor(s:State){return s.phase==='auction'?s.auction!.current:current(s).id}
export function owned(s:State,p:string){return BOARD.filter(t=>s.assets[t.id]?.owner===p)}
export function group(s:State,t:Tile){return BOARD.filter(x=>t.group!==undefined&&x.group===t.group)}
export function fullGroup(s:State,t:Tile,p:string){const g=group(s,t);return g.length>0&&g.every(x=>s.assets[x.id].owner===p&&!s.assets[x.id].mortgaged)}
export function rent(s:State,id:number){const t=BOARD[id],a=s.assets[id];if(!a?.owner||a.mortgaged)return 0;let n=0;if(t.kind==='property')n=t.rent[a.level]*(a.level===0&&fullGroup(s,t,a.owner)?2:1);else {const count=owned(s,a.owner).filter(x=>x.kind===t.kind&&!s.assets[x.id].mortgaged).length;n=t.kind==='transport'?[0,250000,500000,1000000,2000000][count]:(s.dice[0]+s.dice[1])*10000*[0,4,10,15][count]}return Math.round(n*1.1**s.inflation)}
export function canBuild(s:State,id:number,p:string){const t=BOARD[id],a=s.assets[id];return !!a&&a.owner===p&&t.kind==='property'&&a.level<4&&fullGroup(s,t,p)&&group(s,t).every(x=>s.assets[x.id].level>=a.level)&&s.players.find(x=>x.id===p)!.cash>=t.build}
function log(s:State,text:string,kind='info',event?:LogEvent){s.log.push({id:++s.seq,text,kind,event});s.log=s.log.slice(-100)}
function inflation(s:State){const target=Math.floor(Math.min(...s.players.filter(p=>!p.bankrupt).map(p=>p.laps))/5);if(target>s.inflation){s.inflation=target;log(s,`Inflyatsiya! Ijara narxlari endi boshlang‘ich narxning ${(1.1**target*100).toFixed(0)}% ini tashkil etadi.`,'economy',{key:'inflation',percent:Number((1.1**target*100).toFixed(0))})}}
function finish(s:State){s.phase='end';s.card=null;s.tax=0}
function jail(s:State){const p=current(s),from=p.pos;p.pos=10;p.jailed=true;p.jailAttempts=0;s.extra=false;s.doubles=0;s.lastMove={id:++s.seq,player:p.id,from,to:10,steps:0};finish(s);log(s,`${p.name} qamoqqa tushdi.`, 'jail',{key:'jail',player:p.name})}
function move(s:State,steps:number){const p=current(s),from=p.pos,cross=Math.floor((from+steps)/40);p.pos=(from+steps)%40;if(cross){p.cash+=2000000*cross;p.laps+=cross;log(s,`${p.name} Startdan o‘tdi: +${compact(2000000*cross)} so‘m.`, 'money',{key:'bonus',player:p.name,amount:2000000*cross});inflation(s)}s.lastMove={id:++s.seq,player:p.id,from,to:p.pos,steps};land(s)}
function charge(s:State,amount:number,creditor:string|null,resume:'end'|'roll'|'move'='end',steps=0){const p=current(s),paid=Math.min(p.cash,amount);p.cash-=paid;const other=s.players.find(x=>x.id===creditor);if(other)other.cash+=paid;if(paid<amount){s.phase='debt';s.debt={amount:amount-paid,creditor,resume,steps};log(s,`${p.name}: ${compact(amount-paid)} so‘m qarz. Aktivlarni sotish yoki garov kerak.`,'debt',{key:'debt',player:p.name,amount:amount-paid})}else resumeAfter(s,resume,steps)}
function resumeAfter(s:State,resume:'end'|'roll'|'move',steps=0){if(resume==='move'){current(s).jailed=false;current(s).jailAttempts=0;s.extra=false;move(s,steps)}else if(resume==='roll'){current(s).jailed=false;current(s).jailAttempts=0;s.phase='roll'}else finish(s)}
function settleDebt(s:State){if(!s.debt)return;const p=current(s),d=s.debt,paid=Math.min(p.cash,d.amount);p.cash-=paid;d.amount-=paid;const other=s.players.find(x=>x.id===d.creditor);if(other)other.cash+=paid;if(d.amount===0){s.debt=null;resumeAfter(s,d.resume,d.steps)}}
function land(s:State){const p=current(s),t=BOARD[p.pos],a=s.assets[t.id];log(s,`${p.name} — ${t.name}.`,'info',{key:'land',player:p.name,tile:t.id});if(a){if(!a.owner)s.phase='purchase';else if(a.owner!==p.id&&!a.mortgaged){const cost=rent(s,t.id);log(s,`${p.name} ${s.players.find(x=>x.id===a.owner)!.name}ga ${compact(cost)} so‘m ijara to‘laydi.`, 'money',{key:'rent',player:p.name,other:s.players.find(x=>x.id===a.owner)!.name,amount:cost});charge(s,cost,a.owner)}else finish(s)}else if(t.kind==='gojail')jail(s);else if(t.kind==='card'){const deck=s.decks[t.short==='Taqdir'?0:1];s.card=deck.shift()!;deck.push(s.card);s.phase='card'}else if(t.kind==='tax'){s.tax=t.id===4?500000+owned(s,p.id).length*150000:300000+owned(s,p.id).reduce((n,t)=>n+s.assets[t.id].level,0)*100000;s.phase='tax'}else finish(s)}
function advance(s:State){if(s.extra&&!current(s).jailed&&!current(s).bankrupt){s.extra=false;s.phase='roll';return}do{s.turn=(s.turn+1)%s.players.length}while(current(s).bankrupt);s.turnNo++;s.doubles=0;s.extra=false;s.phase='roll';log(s,`Navbat: ${current(s).name}.`,'info',{key:'turn',player:current(s).name})}
function auctionNext(s:State){const a=s.auction!,eligible=s.players.filter(p=>!p.bankrupt&&!a.passed.includes(p.id));if((a.highest&&eligible.length===1)||eligible.length===0){if(a.highest){const p=s.players.find(p=>p.id===a.highest)!;p.cash-=a.bid;s.assets[a.tile].owner=p.id;log(s,`${p.name} auksionda ${BOARD[a.tile].name}ni ${compact(a.bid)} so‘mga oldi.`,'money',{key:'auctionBuy',player:p.name,tile:a.tile,amount:a.bid})}else log(s,'Taklif bo‘lmadi. Mulk bankda qoldi.','info',{key:'noBid'});s.auction=null;finish(s);return}let idx=s.players.findIndex(p=>p.id===a.current);for(let k=0;k<s.players.length;k++){idx=(idx+1)%s.players.length;const p=s.players[idx];if(!p.bankrupt&&!a.passed.includes(p.id)&&p.id!==a.highest){a.current=p.id;return}}}
function assert(ok:unknown,message='Bu amal hozir mumkin emas.'):asserts ok{if(!ok)throw Error(message)}
export function act(previous:State,action:Action,actorId:string,rng:()=>number=Math.random):State{
assert(previous.phase!=='won','O‘yin yakunlangan.');assert(actor(previous)===actorId,'Hozir sizning navbatingiz emas.');const s:State=structuredClone(previous),p=current(s),t=BOARD[p.pos];const kind=action.type;
if(kind==='roll'){assert(s.phase==='roll');const a=1+Math.floor(rng()*6),b=1+Math.floor(rng()*6);s.dice=[a,b];s.rollId++;s.extra=false;log(s,`${p.name} zarik tashladi: ${a} + ${b}${a===b?' — dubl!':''}`,'dice',{key:'roll',player:p.name,a,b});if(p.jailed){p.jailAttempts++;if(a===b){p.jailed=false;p.jailAttempts=0;move(s,a+b)}else if(p.jailAttempts>=3){log(s,'Qamoqdan chiqish: 500 ming so‘m.','info',{key:'jailFee'});charge(s,500000,null,'move',a+b)}else finish(s)}else{s.doubles=a===b?s.doubles+1:0;if(s.doubles===3)jail(s);else{s.extra=a===b;move(s,a+b)}}
}else if(kind==='buy'){assert(s.phase==='purchase'&&!s.assets[t.id].owner);assert(p.cash>=t.price,'Xarid uchun pul yetarli emas.');p.cash-=t.price;s.assets[t.id].owner=p.id;log(s,`${p.name} ${t.name}ni ${compact(t.price)} so‘mga sotib oldi.`,'money',{key:'buy',player:p.name,tile:t.id,amount:t.price});finish(s);
}else if(kind==='skip'){assert(s.phase==='purchase');s.auction={tile:t.id,current:p.id,bid:0,highest:null,passed:[]};s.phase='auction';log(s,`${t.name} auksionga qo‘yildi.`,'info',{key:'auction',tile:t.id});
}else if(kind==='bid'||kind==='pass'){assert(s.phase==='auction');const a=s.auction!,bidder=s.players.find(x=>x.id===actorId)!;if(kind==='bid'){assert(bidder.cash>=a.bid+100000,'Taklif uchun mablag‘ yetmaydi.');a.bid+=100000;a.highest=actorId;log(s,`${bidder.name}: auksion taklifi ${compact(a.bid)} so‘m.`,'info',{key:'bid',player:bidder.name,amount:a.bid})}else a.passed.push(actorId);auctionNext(s);
}else if(kind==='ack'){assert(s.phase==='card'&&s.card!==null);const c=CARDS[s.card];log(s,`${p.name}: ${c.title}.`,'card',{key:'card',player:p.name,card:s.card});s.card=null;if(c.effect==='jail')jail(s);else if(c.effect==='pass'){p.passes++;finish(s)}else if(c.effect==='start'){move(s,40-p.pos)}else{const value=c.usd?Math.round(c.usd*12000*1.1**s.inflation):c.amount??0;if(value<0)charge(s,-value,null);else{p.cash+=value;finish(s)}}
}else if(kind==='payTax'||kind==='usePass'){assert(s.phase==='tax');if(kind==='usePass'){assert(p.passes>0,'Tanish-bilish kartasi yo‘q.');p.passes--;log(s,`${p.name} Tanish-bilish kartasini ishlatdi.`,'info',{key:'pass',player:p.name});finish(s)}else{log(s,`${p.name}: ${compact(s.tax)} so‘m soliq.`,'money',{key:'tax',player:p.name,amount:s.tax});charge(s,s.tax,null)}
}else if(kind==='payJail'){assert(s.phase==='roll'&&p.jailed);charge(s,500000,null,'roll');
}else if(['build','sell','mortgage','redeem'].includes(kind)){assert(['roll','end','debt'].includes(s.phase));const id=action.tile;assert(Number.isInteger(id)&&id!>=0&&id!<40);const tile=BOARD[id!],a=s.assets[id!];assert(a&&a.owner===p.id,'Bu mulk sizniki emas.');const g=group(s,tile);if(kind==='build'){assert(s.phase!=='debt'&&canBuild(s,id!,p.id),'Qurish uchun to‘liq garovsiz guruh, teng daraja va mablag‘ kerak.');p.cash-=tile.build;a.level++;log(s,`${p.name}: ${tile.name}da ${LEVELS[a.level]} qurildi.`,'build',{key:'build',player:p.name,tile:tile.id,level:a.level})}else if(kind==='sell'){assert(a.level>0&&g.every(t=>s.assets[t.id].level<=a.level),'Avval eng yuqori darajali binoni soting.');a.level--;p.cash+=tile.build/2;log(s,`${tile.name}: bino bosqichi sotildi.`,'info',{key:'sell',tile:tile.id})}else if(kind==='mortgage'){assert(!a.mortgaged&&g.every(t=>s.assets[t.id].level===0),'Guruhdagi binolarni avval soting.');a.mortgaged=true;p.cash+=tile.price/2;log(s,`${tile.name} garovga qo‘yildi.`,'info',{key:'mortgage',tile:tile.id})}else{const cost=Math.round(tile.price*.55);assert(s.phase!=='debt'&&a.mortgaged&&p.cash>=cost,'Garovni qaytarish uchun pul yetmaydi.');a.mortgaged=false;p.cash-=cost;log(s,`${tile.name} garovdan chiqarildi.`,'info',{key:'redeem',tile:tile.id})}settleDebt(s);
}else if(kind==='bankrupt'){assert(s.phase==='debt'&&s.debt);const creditor=s.players.find(x=>x.id===s.debt!.creditor);for(const tile of owned(s,p.id)){const a=s.assets[tile.id];p.cash+=a.level*tile.build/2;a.level=0}settleDebt(s);if(s.debt){if(creditor)creditor.cash+=p.cash;p.cash=0;for(const tile of owned(s,p.id)){s.assets[tile.id].owner=creditor?.id??null;if(!creditor)s.assets[tile.id].mortgaged=false}p.bankrupt=true;p.passes=0;s.debt=null;s.extra=false;log(s,`${p.name} bankrot bo‘ldi.`,'debt',{key:'bankrupt',player:p.name});if(s.players.filter(x=>!x.bankrupt).length>1)advance(s);inflation(s)}
}else if(kind==='end'){assert(s.phase==='end');advance(s)}else throw Error('Noma’lum amal.');
const alive=s.players.filter(x=>!x.bankrupt);if(alive.length===1){s.phase='won';s.winner=alive[0].id;log(s,`${alive[0].name} — davra g‘olibi!`,'win',{key:'win',player:alive[0].name})}s.revision++;return s;
}
export function botAction(s:State):Action{const p=s.players.find(p=>p.id===actor(s))!;if(s.phase==='auction')return {type:p.cash-(s.auction!.bid+100000)>=2000000&&s.auction!.bid<BOARD[s.auction!.tile].price*.9?'bid':'pass'};if(s.phase==='purchase')return {type:p.cash-BOARD[p.pos].price>=1500000?'buy':'skip'};if(s.phase==='card')return {type:'ack'};if(s.phase==='tax')return {type:p.passes?'usePass':'payTax'};if(s.phase==='debt'){const assets=owned(s,p.id);const building=assets.filter(t=>s.assets[t.id].level>0).sort((a,b)=>s.assets[b.id].level-s.assets[a.id].level)[0];if(building)return {type:'sell',tile:building.id};const free=assets.find(t=>!s.assets[t.id].mortgaged);return free?{type:'mortgage',tile:free.id}:{type:'bankrupt'}}if(s.phase==='roll')return {type:'roll'};if(s.phase==='end'){const build=owned(s,p.id).find(t=>canBuild(s,t.id,p.id)&&p.cash-t.build>=3000000);return build?{type:'build',tile:build.id}:{type:'end'}}return {type:'end'}}
