'use client';
import { Globe2, Coins, Map, Volume2, Box } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Switch } from './ui/switch';
import { Tabs, TabsList, TabsTrigger } from './ui/tabs';
import { FigurePicker } from './game-menu';
import { usePresentation } from '@/game/preferences';
import type { Currency, Language, Zone } from '@/game/localization';
export function GameSettings({open,onOpenChange,muted,onSound,view3D,onView,figure,onFigure,busy,error}:{open:boolean;onOpenChange:(v:boolean)=>void;muted:boolean;onSound:()=>void;view3D:boolean;onView:(v:boolean)=>void;figure:number;onFigure:(v:number)=>void;busy:boolean;error:string}){
 const {t,language,currency,zone,setLanguage,setCurrency,setZone}=usePresentation();
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="game-dialog preferences-dialog"><DialogTitle>{t('Sozlamalar','Настройки','Settings')}</DialogTitle><DialogDescription>{t('Tanlovlaringiz shu qurilmada saqlanadi.','Ваш выбор сохраняется на этом устройстве.','Your preferences are saved on this device.')}</DialogDescription>
 <div className="preference-field"><label id="language-label"><Globe2 size={19}/>{t('Til','Язык','Language')}</label><Select value={language} onValueChange={v=>setLanguage(v as Language)}><SelectTrigger className="game-select" aria-labelledby="language-label"><SelectValue/></SelectTrigger><SelectContent className="game-select-options"><SelectItem value="uz">O‘zbek tili</SelectItem><SelectItem value="ru">Русский язык</SelectItem><SelectItem value="en">English</SelectItem></SelectContent></Select></div>
 <div className="preference-field"><label id="currency-label"><Coins size={19}/>{t('Valyuta','Валюта','Currency')}</label><Select value={currency} onValueChange={v=>setCurrency(v as Currency)}><SelectTrigger className="game-select" aria-labelledby="currency-label"><SelectValue/></SelectTrigger><SelectContent className="game-select-options"><SelectItem value="UZS">{t('So‘m — UZS','Сум — UZS','Uzbek som — UZS')}</SelectItem><SelectItem value="RUB">{t('Rubl — ₽','Рубль — ₽','Ruble — ₽')}</SelectItem><SelectItem value="USD">{t('Dollar — $','Доллар — $','Dollar — $')}</SelectItem></SelectContent></Select><p>{t('Shartli o‘yin kursi: $1 = 12 000 so‘m; ₽1 = 150 so‘m. Narxlar va hisob birga o‘zgaradi.','Условный игровой курс: $1 = 12 000 сум; ₽1 = 150 сум. Цены и баланс пересчитываются вместе.','Fixed game rates: $1 = 12,000 UZS; ₽1 = 150 UZS. Prices and balances convert together.')}</p></div>
 <div className="zone-preference"><h3><Map size={19}/>{t('O‘yin zonasi','Игровая зона','Game zone')}</h3><Tabs value={zone} onValueChange={v=>setZone(v as Zone)}><TabsList className="zone-options"><TabsTrigger value="main"><img src="/art/uzbek-city.webp" alt=""/><span><strong>{t('Asosiy zona','Основная зона','Main zone')}</strong><small>{t('Biznes shahri','Бизнес-город','Business city')}</small></span></TabsTrigger><TabsTrigger value="samarkand"><img src="/art/samarkand-evening.webp" alt=""/><span><strong>{t('Sharqona zona','Восточная зона','Oriental zone')}</strong><small>{t('Samarqand oqshomi','Вечерний Самарканд','Samarkand evening')}</small></span></TabsTrigger></TabsList></Tabs></div>
 <div className="setting-row"><div><strong><Volume2 size={18}/>{t('O‘yin ovozlari','Звуки игры','Game sounds')}</strong><span>{t('Fon musiqasi va o‘yin effektlari. Suhbat ovozi o‘z tugmasidan boshqariladi.','Музыка и эффекты игры. Звук чата управляется отдельно.','Background music and game effects. Voice chat has its own sound control.')}</span></div><Switch aria-label={t('O‘yin ovozlari','Звуки игры','Game sounds')} className="setting-toggle" checked={!muted} onCheckedChange={onSound}/></div>
 <div className="setting-row"><div><strong><Box size={18}/>{t('Hajmli doska','Объёмная доска','Board perspective')}</strong><span>{t('Kompyuter ko‘rinishi uchun','Для компьютера','For desktop view')}</span></div><Switch aria-label={t('Hajmli doska','Объёмная доска','Board perspective')} className="setting-toggle" checked={view3D} onCheckedChange={onView}/></div>
 <details className="settings-figures"><summary>{t('Figurani almashtirish','Изменить фигурку','Change your piece')}</summary><FigurePicker value={figure} onChange={onFigure} disabled={busy}/></details>{error&&<p className="negative" role="alert">{error}</p>}
 </DialogContent></Dialog>
}
