'use client';
import { motion } from 'motion/react';
import { ArrowRight, Sparkles, Wallet } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { BOARD, CARDS, current, rent, type State, type Action } from '@/game/engine';
import { usePresentation } from '@/game/preferences';
import { cardCopy, tileName, levelName } from '@/game/localization';
import { PropertyArt } from './game-art';
export function TurnDialog({state,open,onClose,canAct,busy,error,send}:{state:State;open:boolean;onClose:()=>void;canAct:boolean;busy:boolean;error:string;send:(a:Action)=>Promise<void>}) {
 const {t,language,money}=usePresentation(),p=current(state),tile=BOARD[p.pos],purchase=state.phase==='purchase',card=state.card===null?null:CARDS[state.card],copy=state.card===null?null:cardCopy(state.card,language);
 const prospect={...state,assets:{...state.assets,[tile.id]:{owner:p.id,level:0,mortgaged:false}}},income=purchase?rent(prospect,tile.id):0,value=card?.usd?Math.round(card.usd*12000*1.1**state.inflation):card?.amount;
 return <Dialog open={open} onOpenChange={v=>!v&&onClose()}><DialogContent className="game-dialog turn-dialog">
 {purchase?<><div className="offer-image"><PropertyArt tile={tile}/></div><div className="offer-kicker">{t('SOTIB OLISH IMKONIYATI','МОЖНО ПРИОБРЕСТИ','AVAILABLE TO BUY')}</div><DialogTitle>{tileName(tile,language)}</DialogTitle><DialogDescription>{t('Bu mulk bo‘sh. Xarid qilsangiz, unga tushgan raqib sizga ijara to‘laydi.','Этот объект свободен. После покупки соперники будут платить вам аренду, попав сюда.','This property is unowned. Buy it and opponents will pay you rent when they land here.')}</DialogDescription>
 <div className="offer-amounts"><div><span>{t('Xarid narxi','Цена покупки','Purchase price')}</span><strong>{money(tile.price)}</strong></div><div className="income"><span>{t('Raqib tushganda daromad','Доход при попадании соперника','Income when an opponent lands')}</span><strong>+{money(income)}</strong></div></div>
 {tile.kind==='utility'&&<p className="offer-note">{t(`Hisob hozirgi zarik yig‘indisi (${state.dice[0]+state.dice[1]}) uchun. Keyingi daromad zariklarga bog‘liq:`,`Расчёт для текущей суммы кубиков (${state.dice[0]+state.dice[1]}). Будущий доход зависит от броска:`,`Based on the current dice total (${state.dice[0]+state.dice[1]}). Future income depends on the roll:`)} {money(rent({...prospect,dice:[1,1]},tile.id))} – {money(rent({...prospect,dice:[6,6]},tile.id))}.</p>}
 {tile.kind==='property'&&<details className="offer-levels"><summary>{t('Qurilishdan keyingi ijara','Аренда после строительства','Rent after building')}</summary>{tile.rent.slice(1).map((v,i)=><div key={i}><span>{levelName(i+1,language)}</span><strong>{money(Math.round(v*1.1**state.inflation))}</strong></div>)}<p>{t(`Har bosqich: ${money(tile.build)}. Bir rangdagi barcha mulklar kerak.`,`Каждый уровень: ${money(tile.build)}. Нужен полный цветовой комплект.`,`Each level: ${money(tile.build)}. A complete color set is required.`)}</p></details>}
 <p className="offer-balance"><Wallet size={17}/>{t('Hisobingiz','Ваш баланс','Your balance')}: <strong>{money(p.cash)}</strong></p>
 {p.cash<tile.price&&<p className="negative">{t(`${money(tile.price-p.cash)} yetmayapti. Auksionda arzonroq taklif berishingiz mumkin.`,`Не хватает ${money(tile.price-p.cash)}. Вы можете предложить меньше на аукционе.`,`You need ${money(tile.price-p.cash)} more. You can bid a lower amount at auction.`)}</p>}
 <div className="offer-buttons"><button className="gold-btn" disabled={!canAct||busy||p.cash<tile.price} onClick={()=>void send({type:'buy'})}>{busy?t('Bajarilmoqda…','Обработка…','Processing…'):t('Sotib olish','Купить','Buy property')}<ArrowRight size={18}/></button><button className="outline-btn" disabled={!canAct||busy} onClick={()=>void send({type:'skip'})}>{t('Olmayman — auksion','Отказаться — аукцион','Decline — start auction')}</button></div>
 </>:card&&copy?<motion.div className="event-card" key={state.card+'-'+state.turnNo} initial={{opacity:0,rotateY:-35,scale:.94}} animate={{opacity:1,rotateY:0,scale:1}} transition={{duration:.35}}><div className={'event-emblem '+(value!==undefined&&value<0?'loss':'')}><Sparkles size={44}/></div><div className="offer-kicker">{tileName(tile,language).toUpperCase()} · {p.name}</div><DialogTitle>{copy.title}</DialogTitle><DialogDescription>{copy.text}</DialogDescription>{value!==undefined&&<strong className={'event-value '+(value<0?'negative':'positive')}>{value>0?'+':''}{money(value)}</strong>}{card.effect&&<p className="event-effect">{card.effect==='pass'?t('1 ta soliqdan ozod qiluvchi karta saqlanadi','Сохранится карта отмены одного налога','Keep a card that cancels one tax'):card.effect==='jail'?t('Qamoqqa o‘tasiz','Вы отправитесь в тюрьму','You go to jail'):t(`Startga o‘tasiz · +${money(2000000)}`,`Вы перейдёте на Старт · +${money(2000000)}`,`Move to Start · +${money(2000000)}`)}</p>}{canAct?<button className="gold-btn full" disabled={busy} onClick={()=>void send({type:'ack'})}>{busy?t('Bajarilmoqda…','Обработка…','Processing…'):t('Qabul qilish va davom etish','Принять и продолжить','Accept and continue')}<ArrowRight size={18}/></button>:<p className="offer-note">{t(`${p.name}ning kartasi. Natija uning hisobiga qo‘llanadi.`,`Карта игрока ${p.name}. Результат применяется к его балансу.`,`${p.name}'s card. The result applies to their balance.`)}</p>}</motion.div>:<><DialogTitle>{t('Navbat yakunlandi','Ход завершён','Turn complete')}</DialogTitle><DialogDescription>{t('O‘yin davom etmoqda.','Игра продолжается.','The game continues.')}</DialogDescription></>}
 {error&&<p className="negative" role="alert">{error}</p>}</DialogContent></Dialog>
}
